### ISSUE TITLE
Is OpenBabel a required or optional dependency?

### ISSUE THREAD

**Issue by mattwthompson** [conda-forge/mbuild-feedstock#15]
Commit fa74c09f198c08f90df2c8498da501e175878baa has caused me some issues in some builds - I can't get to the bottom of it (and would like to avoid doing so, if possible) but it seems like OpenBabel builds are broken in some way that's causing my tests to reliably fail on Python 3.7. I personally am not using its functionality and therefore would like to avoid having it pulled in automatically. If this PR would be accepted, I can write it up. An alternative approach would be to split out the package into `mbuild-base` and `mbuild` such that the "bare minimum" dependencies are installed in `mbuild-base`, which a downstream developer could install without extra optional-ish dependencies, and `mbuild` would depend on `mbuild-base` but pull in OpenBabel and other optional packages that a typical user might benefit from having installed. See some (complicated) examples from [Matplotlib](https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/meta.yaml) and [NumPy](https://github.com/conda-forge/numpy-feedstock/blob/master/recipe/meta.yaml).

**Comment by mattwthompson** [comment]
Related https://github.com/mosdef-hub/mbuild/issues/917

**Comment by daico007** [comment]
Good catch, we will also need to remove `oset` requirement in the next release.

**Comment by mattwthompson** [comment]
Would it break things to make a new build (without a new release) with one or both of these changes?

**Comment by daico007** [comment]
It should not, I will open a PR to remove those 2 dependencies

**Comment by daico007** [comment]
Resolved by #16
